debug: true
font-family:  Minecraft # Consolas
scale: 1

dialog-box:
  delay: 20
  #alpha: 0.3
  endPoint: true
  mode-classic: dialog-box 
  mode-fullscreen: dialog-box-full
  font-size: 32px # default 22px
  font-family: Jura-Font # Minecraft # Jura-Font
  line-height: 32px # default 32px

publish:
  host: http://vnjson.mcap.fun
  token: ffd5e78f5d987ceaa20b2d26da251b7a

menu:
  audio: menu-item
  volume: 0.1
  
main-menu:
  audio: menu-item
  volume: 0.1
  
discord-log:
  webhook: https://discord.com/api/webhooks/995314212500938789/C4ul6cKMwYadYYaOCSyla_dlwDVd1IPSZu0wb24l9kkjo971QCfdHolkEPrExR2KcpzO


# console-port: 8082
# chess: false
paint-board: true
# crossword: false

push: menu-item